"""
Predictive Sharpness from Raw Samples — Histogram Density Conversion
-------------------------------------------------------------------

This script implements a histogram-based workflow for computing the sharpness
measure from raw sample points when no callable density is available.

It is designed to work with the functions in sharpness_multi.py, especially
prepare_array_pdf() and sharpness_multi().

NOTE: THIS IS A TEST SCRIPT, NOT FULLY INVESTIGATED FOR PRACTICAL USE.

NOTE: This script was almost fully autogenerated by AI after it inspected
sharpness_multi.py and instructions were given.


WHAT THIS GIVES YOU
-------------------
1) Conversion of raw sample points into a uniform-grid histogram density array:
   - samples_to_density_array(samples, bounds, bins, ...)
     → Converts raw sample points into a piecewise-constant density array on a
       uniform grid over the chosen bounded domain.

2) Optional handling of weighted samples:
   - weights=...
     → Supports nonnegative sample weights when constructing the histogram.

3) Optional domain filtering:
   - drop_outside=True / False
     → Either discard samples outside the chosen bounds or raise an error if
       out-of-bounds samples are present.

4) Optional pseudocount smoothing:
   - add_epsilon=...
     → Adds a nonnegative pseudocount to every histogram bin before density
       normalization. Usually leave at 0.0 unless you explicitly want to reduce
       zero bins.

5) Direct sharpness computation from raw samples:
   - sharpness_from_samples_histogram(samples, bounds, bins, ...)
     → Builds the histogram density, prepares it for the sharpness routines,
       and computes the sharpness score using sharpness_multi().

INTERPRETATION
--------------
All sharpness scores are normalized to [0, 1]:
- 0   → maximally diffuse (uniform distribution over the domain)
- 1   → maximally sharp (degenerate / Dirac-like prediction)

ASSUMPTIONS / REQUIREMENTS
--------------------------
- Input samples must be raw sample points with shape:
    * (n_samples,) for 1D, or
    * (n_samples, d) for multidimensional cases

- The domain must be bounded and specified as:
    bounds = [(a1, b1), ..., (ad, bd)]

- The histogram is built on a uniform grid:
    * bins may be an integer or a list of integers
    * the resulting density is piecewise constant on the grid cells

- If weights are supplied:
    * they must be finite, nonnegative, and have the same length as samples

- If normalize=True:
    * the returned density array integrates to 1 over the bounded domain

- This is a histogram approximation, not an exact density recovery:
    * results depend on the choice of bounds and bin counts
    * coarser bins give rougher approximations
    * finer bins give more detailed approximations but may be sparse

PRACTICAL TIPS
--------------
- Use this script when you have raw sample draws but no analytic or callable PDF.
- Choose bounds that represent the full target domain for the sharpness score.
- Use drop_outside=True if samples outside the target bounds should simply be ignored.
- Use drop_outside=False if you want strict checking of domain consistency.
- Use add_epsilon=0.0 unless you intentionally want to smooth away exact zero bins.
- The quality of the sharpness estimate depends strongly on the histogram grid:
    * too few bins may oversmooth the distribution
    * too many bins may produce sparse, noisy density arrays
- In higher dimensions, keep in mind that histogram grids become coarse quickly
  unless the sample size is very large.

TYPICAL WORKFLOWS
-----------------
1) Raw samples → histogram density array:
    density_array, coords = samples_to_density_array(
        samples,
        bounds=[(0.0, 1.0)] * d,
        bins=10,
        return_coords=True
    )

2) Raw samples → sharpness directly:
    score = sharpness_from_samples_histogram(
        samples,
        bounds=[(0.0, 1.0)] * d,
        bins=10
    )

3) Weighted samples → sharpness:
    score = sharpness_from_samples_histogram(
        samples,
        bounds=bounds,
        bins=bins,
        weights=weights
    )

4) Diagnostics / inspection:
    score, details = sharpness_from_samples_histogram(
        samples,
        bounds=bounds,
        bins=bins,
        return_details=True
    )

    print(details["histogram_info"]["n_samples_inside"])
    print(details["density_array_shape"])

IMPORTANT NOTE
--------------
This script estimates a density by histogramming raw samples. It does not use
Monte Carlo evaluation of a callable PDF, and it does not assume midpoint-grid
density values are already available. Instead, it constructs the density array
from the sample cloud first, then passes that array into the standard sharpness
pipeline.

EXAMPLE
-------
An example using a raw 10D sample cloud is included at the bottom of this file.
It is commented out — uncomment and adapt the example block to run it.
"""


import numpy as np


def samples_to_density_array(
    samples,
    bounds,
    bins,
    weights=None,
    drop_outside=True,
    normalize=True,
    add_epsilon=0.0,
    return_coords=False,
    return_info=False
):
    """
    Convert raw sample points into a uniform-grid histogram density array
    suitable for prepare_array_pdf() and sharpness_multi().

    Parameters
    ----------
    samples : array_like, shape (n_samples, d) or (n_samples,)
        Raw sample points in the domain.
    bounds : list of (float, float)
        Domain bounds [(a1, b1), ..., (ad, bd)].
    bins : int or list of ints
        Number of bins per dimension.
    weights : array_like, optional
        Optional nonnegative sample weights.
    drop_outside : bool, default=True
        If True, discard samples outside bounds.
        If False, raise ValueError when out-of-bounds samples are present.
    normalize : bool, default=True
        If True, return a density array integrating to 1 over the bounded domain.
    add_epsilon : float, default=0.0
        Optional nonnegative pseudocount added to every bin before normalization.
        Usually leave at 0.0 unless you explicitly want smoothing away from zero bins.
    return_coords : bool, default=False
        If True, also return midpoint coordinate arrays.
    return_info : bool, default=False
        If True, also return diagnostics.

    Returns
    -------
    density_array : ndarray
        Histogram density array on a uniform grid.
    coords : list of ndarray, optional
        Midpoint coordinates for each dimension.
    info : dict, optional
        Diagnostics.

    Notes
    -----
    This function estimates a piecewise-constant density via histogramming.
    It is appropriate when you have raw sample points but no callable density.

    Typical workflow:
        density_array, coords = samples_to_density_array(samples, bounds, bins, return_coords=True)
        prepared = prepare_array_pdf(density_array, coords, bounds=bounds, normalize=True)
        score = sharpness_multi(prepared, mode="simplified")
    """
    samples = np.asarray(samples, dtype=float)
    if samples.ndim == 1:
        samples = samples[:, None]

    n_samples, d = samples.shape

    bounds = np.asarray(bounds, dtype=float)
    if bounds.shape != (d, 2):
        raise ValueError(f"bounds must have shape ({d}, 2), got {bounds.shape}")

    if np.isscalar(bins):
        bins = [int(bins)] * d
    bins = np.asarray(bins, dtype=int)
    if bins.shape != (d,):
        raise ValueError(f"bins must have length {d}")
    if np.any(bins < 1):
        raise ValueError("All bin counts must be >= 1")

    lower = bounds[:, 0]
    upper = bounds[:, 1]
    widths = upper - lower
    if np.any(widths <= 0):
        raise ValueError("Each upper bound must exceed the lower bound")

    if weights is not None:
        weights = np.asarray(weights, dtype=float).ravel()
        if weights.shape[0] != n_samples:
            raise ValueError("weights must have the same length as samples")
        if np.any(~np.isfinite(weights)):
            raise ValueError("weights must be finite")
        if np.any(weights < 0):
            raise ValueError("weights must be nonnegative")

    inside = np.all((samples >= lower) & (samples <= upper), axis=1)
    n_inside = int(np.sum(inside))
    n_outside = int(n_samples - n_inside)

    if n_outside > 0 and not drop_outside:
        raise ValueError(f"{n_outside} sample points fall outside bounds")

    samples_in = samples[inside]
    if weights is None:
        weights_in = None
        total_weight = float(n_inside)
    else:
        weights_in = weights[inside]
        total_weight = float(np.sum(weights_in))

    if samples_in.shape[0] == 0 or total_weight <= 0:
        raise ValueError("No positive sample mass falls inside bounds")

    # Histogram counts / weighted counts
    hist, edges = np.histogramdd(
        samples_in,
        bins=bins,
        range=[tuple(b) for b in bounds],
        weights=weights_in
    )

    if add_epsilon < 0:
        raise ValueError("add_epsilon must be nonnegative")
    if add_epsilon > 0:
        hist = hist + float(add_epsilon)

    # Convert counts to density
    cell_widths = widths / bins
    cell_volume = float(np.prod(cell_widths))

    if normalize:
        total_mass = float(np.sum(hist))
        if total_mass <= 0:
            raise ValueError("Histogram has zero total mass after processing")
        density_array = hist / (total_mass * cell_volume)
    else:
        density_array = hist / cell_volume

    # Midpoint coordinates for each axis
    coords = [
        0.5 * (edges[i][:-1] + edges[i][1:])
        for i in range(d)
    ]

    outputs = [density_array]

    if return_coords:
        outputs.append(coords)

    if return_info:
        info = {
            "dimension": d,
            "n_samples_total": int(n_samples),
            "n_samples_inside": int(n_inside),
            "n_samples_outside": int(n_outside),
            "outside_fraction": float(n_outside / n_samples),
            "bins": bins.copy(),
            "bounds": bounds.copy(),
            "cell_volume": cell_volume,
            "normalize": bool(normalize),
            "add_epsilon": float(add_epsilon),
            "total_hist_mass_before_density_scaling": float(np.sum(hist)),
        }
        outputs.append(info)

    if len(outputs) == 1:
        return outputs[0]
    return tuple(outputs)

def sharpness_from_samples_histogram(
    samples,
    bounds,
    bins,
    weights=None,
    mode="simplified",
    drop_outside=True,
    normalize=True,
    add_epsilon=0.0,
    return_details=False
):
    """
    Estimate sharpness from raw sample points by:
      1) building a histogram density array on a uniform grid,
      2) preparing the array,
      3) computing sharpness with sharpness_multi().

    Parameters
    ----------
    samples : array_like
        Raw sample points, shape (n_samples, d) or (n_samples,).
    bounds : list of (float, float)
        Domain bounds.
    bins : int or list of ints
        Number of bins per dimension.
    weights : array_like, optional
        Optional nonnegative sample weights.
    mode : str, default='simplified'
        Sharpness mode for sharpness_multi().
    drop_outside : bool, default=True
        Drop samples outside bounds.
    normalize : bool, default=True
        Normalize histogram to integrate to 1.
    add_epsilon : float, default=0.0
        Optional pseudocount per bin.
    return_details : bool, default=False
        If True, return diagnostics and intermediate objects.

    Returns
    -------
    score : float
        Sharpness score.
    details : dict, optional
        Extra diagnostics.
    """
    density_array, coords, hist_info = samples_to_density_array(
        samples=samples,
        bounds=bounds,
        bins=bins,
        weights=weights,
        drop_outside=drop_outside,
        normalize=normalize,
        add_epsilon=add_epsilon,
        return_coords=True,
        return_info=True
    )

    prepared = prepare_array_pdf(
        density_array,
        coords,
        bounds=bounds,
        normalize=normalize,
        return_coords=False
    )

    score = sharpness_multi(prepared, mode=mode)

    if return_details:
        details = {
            "histogram_info": hist_info,
            "density_array_shape": density_array.shape,
            "prepared_size": int(np.asarray(prepared).size),
            "mode": mode,
            "density_array": density_array,
            "coords": coords,
            "prepared": prepared,
        }
        return score, details

    return score



# Example: raw 10D sample cloud
# rng = np.random.default_rng(42)
# samples = rng.normal(loc=0.5, scale=0.15, size=(50000, 10))
#
# score, details = sharpness_from_samples_histogram(
#    samples=samples,
#    bounds=[(0.0, 1.0)] * 10,
#    bins=3,
#    mode="simplified",
#    drop_outside=True,
#    normalize=True,
#    return_details=True
# )
#
# print("Sharpness:", score)
# print("Used samples inside bounds:", details["histogram_info"]["n_samples_inside"])
