"""
Predictive Sharpness for High-Dimensional Cases — Monte Carlo / Quasi-Monte Carlo
---------------------------------------------------------------------------------

This script implements a high-dimensional estimator of the sharpness measure S(f)
from the paper:
"A Measure of Predictive Sharpness for Probabilistic Models".

It is designed for cases where full tensor-grid discretization is impractical,
and instead estimates sharpness by sampling the bounded outcome domain Omega,
evaluating the PDF at those sampled points, and computing sharpness from the
sampled density heights using the fast sorted empirical Gini mean-difference.

NOTE: This script works approximately with sharpness_multi.py visualizations,
compatibility with rearranged_formulas.py, c_plot.py, and c_plot_multiple.py
has not yet been built.

NOTE: This script was almost fully autogenerated by AI, after it inspected
sharpness_multi.py and instructions were given.

WHAT THIS GIVES YOU
-------------------
1) Robust batch evaluation of callable PDFs:
   - _evaluate_pdf_batch(pdf, pts, vectorized=None)
     → Evaluates a PDF on batches of domain points, with optional fallback
       from vectorized to pointwise evaluation.

2) Cleaning of sampled density values:
   - _clean_density_values(vals, clip_negative=True, pos_inf_scale=1e6)
     → Cleans raw density evaluations:
       * NaN and -inf → 0
       * +inf → large finite spike
       * optional clipping of negative values to 0

3) Monte Carlo / quasi-Monte Carlo domain samplers:
   - _make_sampler(bounds, sampler="sobol" | "halton" | "lhs" | "random", ...)
     → Generates points in [0,1]^d and maps them to the bounded domain.

4) Sharpness from sampled density values:
   - sharpness_from_density_samples(density_samples, domain_volume=1.0, ...)
     → Computes sharpness directly from sampled density heights.

5) Main high-dimensional sharpness estimator:
   - sharpness_multi_mc(pdf, bounds, n_samples=65536, ...)
     → Estimates sharpness for one or multiple PDFs by:
       * sampling the bounded domain,
       * evaluating the PDF(s) at those domain points,
       * computing sharpness from the sampled density values.

INTERPRETATION
--------------
All sharpness scores are normalized to [0, 1]:
- 0   → maximally diffuse (uniform distribution over the domain)
- 1   → maximally sharp (degenerate / Dirac-like prediction)

ASSUMPTIONS / REQUIREMENTS
--------------------------
- The domain must be bounded and given as a hyper-rectangle:
    bounds = [(a1, b1), ..., (ad, bd)]

- Input PDFs must be callable and evaluable on the domain.
  They may be:
    * vectorized, accepting shape (m, d) input and returning shape (m,), or
    * pointwise, in which case vectorized=False or automatic fallback may be used.

- The estimator samples the *domain*, not the predictive distribution.
  That is, it uses points U_i drawn uniformly or quasi-uniformly over Omega,
  then evaluates f(U_i).

- If normalization="assume":
    * the callable is assumed to already integrate to 1 over the given bounds

- If normalization="estimate":
    * the callable may be proportional to a PDF, and normalization is estimated
      from the same sampled density values

PRACTICAL TIPS
--------------
- Use sampler="sobol" as the default for smooth directly evaluable PDFs.
- For Sobol sampling, powers of two are often preferable; this script can
  automatically round n_samples up to the next power of two.
- Increase n_samples for higher accuracy.
- Use batch_size to reduce memory usage for expensive or high-dimensional PDFs.
- Use normalization="assume" whenever the PDF is already correctly normalized
  over the chosen bounds.
- Use return_details=True to inspect diagnostics such as the estimated integral
  over the domain.
- Use return_density_samples=True if you want to pass the sampled density values
  to sharpness_multi(...) or visualize_sharpness(...) for approximate visual
  inspection, noting that these samples are not midpoint-grid values.

TYPICAL WORKFLOWS
-----------------
1) Normalized high-dimensional PDF → Sharpness:
    bounds = [(0.0, 1.0)] * 10
    score = sharpness_multi_mc(my_pdf, bounds, n_samples=65536)

2) Unnormalized callable proportional to a PDF → Sharpness:
    score = sharpness_multi_mc(
        my_unnormalized_pdf,
        bounds,
        normalization="estimate"
    )

3) Multiple PDFs on the same sampled domain:
    scores = sharpness_multi_mc([pdf1, pdf2, pdf3], bounds, n_samples=65536)

4) Diagnostics / debugging:
    score, details = sharpness_multi_mc(
        my_pdf,
        bounds,
        return_details=True,
        return_density_samples=True
    )

    print(details["per_pdf"]["estimated_integral_over_domain"])

5) Optional approximate visualization of sampled density heights (with sharpness_multi.py):
    density_samples = details["per_pdf"]["density_samples"]
    print(sharpness_multi(density_samples, mode="gini"))
    visualize_sharpness(density_samples, ["High-D PDF"], mode="gini")

EXAMPLE
-------
An example using a 10D truncated normalized Gaussian-like density is included
at the bottom of this file. Uncomment to run.
"""


import numpy as np
import warnings
from math import erf

try:
    from scipy.stats import qmc
except Exception:
    qmc = None


# === MC HELPERS ===============================================================

def _is_power_of_two(n):
    return (n > 0) and (n & (n - 1) == 0)


def _next_power_of_two(n):
    return 1 if n <= 1 else 2 ** int(np.ceil(np.log2(n)))


def _clean_density_values(vals, clip_negative=True, pos_inf_scale=1e6):
    """
    Clean raw density evaluations:
      - NaN, -inf -> 0
      - +inf -> large finite spike
      - negatives optionally clipped to 0
    """
    vals = np.asarray(vals, dtype=float).ravel().copy()

    nan_mask = np.isnan(vals)
    neg_inf_mask = vals == -np.inf
    pos_inf_mask = vals == np.inf

    if np.any(pos_inf_mask):
        finite_mask = np.isfinite(vals)
        if np.any(finite_mask):
            max_finite = np.max(vals[finite_mask])
            replacement_value = max(max_finite * pos_inf_scale, pos_inf_scale)
        else:
            replacement_value = pos_inf_scale
        vals[pos_inf_mask] = replacement_value

    vals[nan_mask | neg_inf_mask] = 0.0

    if clip_negative:
        vals = np.clip(vals, 0.0, None)

    return vals


def _evaluate_pdf_batch(pdf, pts, vectorized=None, errors_to_zero=True):
    """
    Evaluate a PDF on a batch of points.

    Parameters
    ----------
    pdf : callable
        Callable accepting either:
          - pts with shape (m, d), returning shape (m,), or
          - pointwise inputs if vectorized=False fallback is used.
    pts : ndarray, shape (m, d)
    vectorized : bool or None
        - True: require vectorized evaluation
        - False: use pointwise fallback
        - None: try vectorized first, then fallback
    errors_to_zero : True/False
        If True, evaluation failures at individual points are treated as zero
        density instead of raising.

    Returns
    -------
    vals : ndarray, shape (m,)
    """
    pts = np.asarray(pts, dtype=float)
    m, d = pts.shape

    def _coerce_output(out):
        out = np.asarray(out, dtype=float)
        if out.ndim == 0:
            return np.full(m, float(out), dtype=float)
        out = out.ravel()
        if out.size != m:
            raise ValueError(f"PDF returned {out.size} values for a batch of size {m}.")
        return out

    def _pointwise_eval():
        vals = np.empty(m, dtype=float)
        for i in range(m):
            x = pts[i]
            try:
                vals[i] = pdf(x)
            except Exception:
                try:
                    if d == 1:
                        vals[i] = pdf(float(x[0]))
                    else:
                        raise
                except Exception:
                    if errors_to_zero:
                        vals[i] = 0.0
                    else:
                        raise
        return vals

    if vectorized is False:
        vals = _pointwise_eval()
        return vals

    try:
        out = pdf(pts) if d > 1 else pdf(pts[:, 0])
        vals = _coerce_output(out)
        return vals
    except Exception:
        if vectorized is True and not errors_to_zero:
            raise
        vals = _pointwise_eval()
        return vals

def _make_sampler(bounds, sampler="sobol", scramble=True, seed=None):
    """
    Return a callable draw_unit(n) that generates points in [0,1]^d.
    """
    bounds = np.asarray(bounds, dtype=float)
    d = bounds.shape[0]

    if isinstance(seed, np.random.Generator):
        rng = seed
        qmc_seed = int(rng.integers(0, 2**32 - 1))
    else:
        rng = np.random.default_rng(seed)
        qmc_seed = seed

    sampler = sampler.lower()

    if sampler == "random":
        def draw_unit(n):
            return rng.random((n, d))
        return draw_unit

    if qmc is None:
        warnings.warn(
            f"scipy.stats.qmc is not available; falling back from sampler='{sampler}' to sampler='random'."
        )
        def draw_unit(n):
            return rng.random((n, d))
        return draw_unit

    if sampler == "sobol":
        engine = qmc.Sobol(d=d, scramble=scramble, seed=qmc_seed)
        def draw_unit(n):
            return engine.random(n)
        return draw_unit

    if sampler == "halton":
        engine = qmc.Halton(d=d, scramble=scramble, seed=qmc_seed)
        def draw_unit(n):
            return engine.random(n)
        return draw_unit

    if sampler in {"lhs", "latin", "latin_hypercube"}:
        # LHS is best generated in one shot, but repeated random(n) calls are still usable in practice.
        engine = qmc.LatinHypercube(d=d, scramble=scramble, seed=qmc_seed)
        def draw_unit(n):
            return engine.random(n)
        return draw_unit

    raise ValueError("sampler must be one of: 'sobol', 'halton', 'lhs', 'random'")


def sharpness_from_density_samples(
    density_samples,
    domain_volume=1.0,
    normalization="assume",
    clip=True
):
    """
    Compute sharpness from density values sampled at domain points.

    This is the Monte Carlo / QMC estimator based on the empirical Gini
    mean-difference of the sampled density heights, computed via sorting.

    Parameters
    ----------
    density_samples : array_like
        1D array of density evaluations y_i = f(U_i), where U_i are sampled
        from the domain (typically uniformly or quasi-uniformly).
    domain_volume : float, default=1.0
        Volume |Omega| of the bounded domain.
    normalization : {'assume', 'estimate'}, default='assume'
        - 'assume'   : assume the PDF integrates to 1 on the domain.
        - 'estimate' : treat the callable as possibly unnormalized and estimate
                       the normalization from the same sampled values.
    clip : bool, default=True
        If True, clip the final score to [0, 1].

    Returns
    -------
    score : float
        Sharpness estimate.

    Notes
    -----
    If Y_i = f(U_i) with U_i sampled uniformly over Omega, then:
        S(f) = (|Omega| / 2) E|Y - Y'|
    and the empirical estimator is
        S_hat = |Omega| * sum_i c_i Y_(i) / [m(m-1)],
    where Y_(i) are sorted density values and
        c_i = 2i - m - 1   for i = 1,...,m.

    For unnormalized g instead of f, use normalization='estimate', yielding
        S_hat = sum_i c_i g_(i) / [m(m-1) * mean(g)].
    """
    y = np.asarray(density_samples, dtype=float).ravel()
    m = y.size
    if m < 2:
        raise ValueError("At least two sampled density values are required.")

    y_sorted = np.sort(y)
    coeffs = 2.0 * np.arange(m, dtype=float) - m + 1.0  # 0-based version of (2i - m - 1)
    weighted_sum = float(np.dot(coeffs, y_sorted))

    normalization = normalization.lower()
    if normalization == "assume":
        score = domain_volume * weighted_sum / (m * (m - 1))
    elif normalization == "estimate":
        mean_y = float(np.mean(y))
        if mean_y <= 0:
            raise ValueError("Cannot estimate normalization: sampled mean density is non-positive.")
        score = weighted_sum / (m * (m - 1) * mean_y)
    else:
        raise ValueError("normalization must be 'assume' or 'estimate'")

    if clip:
        score = float(np.clip(score, 0.0, 1.0))
    return float(score)


# === MAIN HIGH-D SHARPNESS FUNCTION ==========================================

def sharpness_multi_mc(
    pdf,
    bounds,
    n_samples=65536,
    sampler="sobol",
    scramble=True,
    seed=None,
    batch_size=None,
    normalization="assume",
    vectorized=None,
    clip_negative=True,
    pos_inf_scale=1e6,
    sobol_power_of_two=True,
    clip=True,
    return_details=False,
    return_density_samples=False
):
    """
    Estimate multidimensional sharpness for high-dimensional PDFs by:
      1) sampling the bounded domain Omega,
      2) evaluating the PDF at those sample points,
      3) computing sharpness from the sampled density heights using the
         fast sorted empirical Gini mean-difference.

    This is intended for high-dimensional cases where full tensor-grid
    discretization is impractical.

    Parameters
    ----------
    pdf : callable or list of callables
        Density function(s). Each callable should accept:
          - points of shape (m, d) and return shape (m,), or
          - pointwise input if vectorized=False fallback is used.
    bounds : list of (float, float)
        Hyper-rectangular domain bounds [(a1, b1), ..., (ad, bd)].
    n_samples : int, default=65536
        Number of domain samples to use. Larger gives lower MC/QMC error.
    sampler : {'sobol', 'halton', 'lhs', 'random'}, default='sobol'
        Domain sampler. 'sobol' is typically the best default for high-d
        bounded boxes when the PDF is directly evaluable.
    scramble : bool, default=True
        Whether to scramble the QMC sequence (Sobol/Halton/LHS).
    seed : int or numpy.random.Generator, optional
        Reproducibility control.
    batch_size : int or None, default=None
        Number of domain points to evaluate per batch. If None, uses all
        points in one batch. Batching reduces peak memory.
    normalization : {'assume', 'estimate'}, default='assume'
        - 'assume'   : assume the callable already integrates to 1 over bounds.
        - 'estimate' : allow an unnormalized callable and estimate the
                       normalization from the same domain sample.
    vectorized : bool or None, default=None
        - True  : require vectorized PDF evaluation
        - False : force pointwise evaluation
        - None  : try vectorized, then fallback to pointwise
    clip_negative : bool, default=True
        Clip negative density evaluations to zero.
    pos_inf_scale : float, default=1e6
        Replacement scale for +inf values.
    sobol_power_of_two : bool, default=True
        If sampler='sobol' and n_samples is not a power of two, round up to
        the next power of two for better Sobol balance properties.
    clip : bool, default=True
        Clip the final sharpness estimate(s) to [0, 1].
    return_details : bool, default=False
        If True, return a diagnostics dictionary in addition to the score(s).
    return_density_samples : bool, default=False
        If True, include the sampled density values in the diagnostics dict.
        Useful for debugging / uncertainty analysis, but can use extra memory.

    Returns
    -------
    score : float or list of float
        Sharpness estimate(s).
    details : dict, optional
        Returned only if return_details=True.

    Notes
    -----
    Important:
    - This function samples the *domain*, not the forecast distribution.
    - It does NOT call sharpness_multi(), because Monte Carlo sampled density
      values are not midpoint-grid cell values.
    - Multiple PDFs are evaluated on the SAME sampled domain points for more
      stable comparisons.

    Best practice:
    - Use sampler='sobol' (or 'halton') for smooth, directly evaluable PDFs.
    - Use normalization='assume' if the PDF is already normalized over bounds.
    - Use normalization='estimate' if the callable is proportional to a PDF.
    """
    bounds = np.asarray(bounds, dtype=float)
    if bounds.ndim != 2 or bounds.shape[1] != 2:
        raise ValueError("bounds must be an array-like of shape (d, 2).")

    lower = bounds[:, 0]
    upper = bounds[:, 1]
    widths = upper - lower

    if np.any(widths <= 0):
        raise ValueError("All upper bounds must be greater than lower bounds.")

    d = bounds.shape[0]
    domain_volume = float(np.prod(widths))

    if not np.isscalar(n_samples) or int(n_samples) < 2:
        raise ValueError("n_samples must be an integer >= 2.")
    n_samples = int(n_samples)

    sampler = sampler.lower()
    if sampler == "sobol" and sobol_power_of_two and not _is_power_of_two(n_samples):
        n_used = _next_power_of_two(n_samples)
    else:
        n_used = n_samples

    if batch_size is None:
        batch_size = n_used
    batch_size = int(batch_size)
    if batch_size < 1:
        raise ValueError("batch_size must be >= 1.")

    # Single PDF or multiple PDFs
    if callable(pdf):
        pdfs = [pdf]
        single = True
    elif isinstance(pdf, (list, tuple)):
        if len(pdf) == 0:
            raise ValueError("pdf list is empty.")
        if not all(callable(f) for f in pdf):
            raise TypeError("All elements of pdf list must be callables.")
        pdfs = list(pdf)
        single = False
    else:
        raise TypeError("pdf must be a callable or list of callables.")

    draw_unit = _make_sampler(bounds, sampler=sampler, scramble=scramble, seed=seed)

    # Preallocate sampled density values for each PDF
    density_samples = [np.empty(n_used, dtype=float) for _ in pdfs]

    # Sample the domain and evaluate PDFs in batches
    start = 0
    while start < n_used:
        stop = min(start + batch_size, n_used)
        n_batch = stop - start

        unit_pts = draw_unit(n_batch)
        pts = lower + unit_pts * widths

        for k, f in enumerate(pdfs):
            vals = _evaluate_pdf_batch(f, pts, vectorized=None, errors_to_zero=True)
            vals = _clean_density_values(
                vals,
                clip_negative=clip_negative,
                pos_inf_scale=pos_inf_scale
            )
            density_samples[k][start:stop] = vals

        start = stop

    # Compute sharpness from sampled density heights
    scores = []
    per_pdf_details = []

    for y in density_samples:
        score = sharpness_from_density_samples(
            y,
            domain_volume=domain_volume,
            normalization=normalization,
            clip=clip
        )
        scores.append(score)

        detail = {
            "sample_mean_density": float(np.mean(y)),
            "sample_min_density": float(np.min(y)),
            "sample_max_density": float(np.max(y)),
            "estimated_integral_over_domain": domain_volume * float(np.mean(y)),
        }
        if return_density_samples:
            detail["density_samples"] = y.copy()
        per_pdf_details.append(detail)

    if single:
        scores_out = scores[0]
        per_pdf_out = per_pdf_details[0]
    else:
        scores_out = scores
        per_pdf_out = per_pdf_details

    if return_details:
        details = {
            "dimension": d,
            "domain_volume": domain_volume,
            "bounds": bounds.copy(),
            "sampler": sampler,
            "scramble": bool(scramble),
            "seed": seed,
            "n_requested": n_samples,
            "n_used": n_used,
            "batch_size": batch_size,
            "normalization": normalization,
            "vectorized": vectorized,
            "clip_negative": bool(clip_negative),
            "sobol_power_of_two": bool(sobol_power_of_two),
            "per_pdf": per_pdf_out,
        }
        return scores_out, details

    return scores_out


# EXAMPLE - 10D PDF
# def pdf_10d_truncated_normalized(x):
#    x = np.asarray(x, dtype=float)
#    if x.ndim == 1:
#        x = x[None, :]
#
#    # Truncation domain: [0,1]^10
#    inside = np.all((x >= 0.0) & (x <= 1.0), axis=1)
#
#    mu = 0.5
#    sigma2 = 0.08
#    sigma = np.sqrt(sigma2)
#
#    vals = np.zeros(x.shape[0], dtype=float)
#    if not np.any(inside):
#        return vals
#
#    diff = x[inside] - mu
#    quad = np.sum(diff * diff, axis=1)
#    raw = np.exp(-0.5 * quad / sigma2)
#
#    # Exact 1D truncation constant over [0,1]
#    z1 = sigma * np.sqrt(2.0 * np.pi) * erf(0.5 / (np.sqrt(2.0) * sigma))
#
#    # Exact 10D truncation constant over [0,1]^10
#    Z = z1 ** 10
#
#    vals[inside] = raw / Z
#    return vals
#
# bounds = [(0.0, 1.0)] * 10
#
# score, details = sharpness_multi_mc(
#    pdf_10d_truncated_normalized,
#    bounds,
#    n_samples=65536,
#    sampler="sobol",
#    scramble=True,
#    normalization="assume",
#    batch_size=8192,
#    return_details=True,
#    return_density_samples=True   ## True if visualization
# )
#
# density_samples = details["per_pdf"]["density_samples"]   ## Add if visualization
# 
# print("Sharpness:", score)
# print("Estimated integral over domain:", details["per_pdf"]["estimated_integral_over_domain"])
#
# print("Sharpness visualization:", sharpness_multi(density_samples, mode="simplified"))   ## Add if visualization
# visualize_sharpness(density_samples, ["10D PDF"], mode="cplot", zoom_y=0.0)   ## Add if visualization
